# this is wokrflow name
name:hello


#runs on the trigger
on:
  push:
     branches: [main]

    

#these are the jobs inside the workflows 
jobs:

  #this os the name of the job
  greet:

    #this is the github runnner ,each jobs runs on the runner  
    runs-on:ubuntu-latest
    steps:
      - name:say hello to user
        run:echo 'hello frnd'

     - name:say hello to username
       run:echo hello '$user'
