# this is wokrflow name
name:Ashish


#runs on the trigger
on:
 push:
  branches:[main]

#these are the jobs inside the workflows 
greet:
 run-on:ubuntu-latest
 steps:
    -name:say hello to user
     run:echo 'hello frnd'

    -name:say hello to username
     run:echo hello '$user'
