# this is workflow name
name: hello

# runs on the trigger
on:
  # push:
   # branches: [main]
   workflow_dispatch: 

# these are the jobs inside the workflows
jobs:

  # this is the name of the job
  greet:

    # this is the GitHub runner, each job runs on the runner
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "hello friend"

      - name: Say hello to username
        run: echo "hello $USER"
