# API Keys,Sensitive data,credentials
#gitleaks(secret scan)

name: Secret Scan

on:
  workflow_call:

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # fetch full history for better scanning
          fetch-depth: 0

      - name: Run Gitleaks Scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: only needed for org license
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
                
