# this is workflow name
name: hello

# runs on the trigger
on:
  push:
    branches: [main]

# these are the jobs inside the workflows
jobs:

  # first job
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "hello friend"

      - name: Say hello to username
        run: echo "hello $USER"

  # second job
  details:
    runs-on: ubuntu-latest

    steps:
      - name: Show version of docker and python
        run: docker --version && python --version
